version: "1.0"
info:
  model: int-scaffold
packages:
- name: RAHS_16thJan_001Project
  gitServerName: RAHSNoSpace
  gitUrl: https://github.com/rahuldemocenter/RAHS_16thJan_001Project
  gitUsername: rahuldemocenter
  gitBranch: main
services:
- serviceName: project.rahs_16thjan_001.integrations:TestDebugEFS
  packages:
  - name: RAHS_16thJan_001Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.714
